# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:adb926f5f33916a95f7f91ffef68b248aa0008a4eeb084246e9ddf984e79dbfd
# To regenerate: alef generate
# To verify freshness: alef verify

# frozen_string_literal: true

Gem::Specification.new do |spec|
  spec.name = "structuredmerge_host_prototype"
  spec.version = "0.2.0"
  spec.authors       = ["Peter Boling"]
  spec.summary       = "Generated Ruby host-provider prototype for StructuredMerge"
  spec.description   = "Generated Ruby host-provider prototype for StructuredMerge"
  spec.homepage      = "https://github.com/structuredmerge/structuredmerge"

  spec.license       = "AGPL-3.0-or-later"

  spec.required_ruby_version = ">= 3.2.0"
  spec.metadata["rubygems_mfa_required"] = "true"

  candidate_files    = Dir.glob(%w[README* LICENSE* lib/**/* ext/**/* sig/**/* Steepfile]).select { |f| File.file?(f) }
  spec.files         = candidate_files.grep_v(%r{/(?:target|tmp)/|\.(?:bundle|so|dylib|dll|o|a|log)\z|\.dSYM/})
  spec.require_paths = ["lib"]
  spec.extensions    = ["ext/structuredmerge_host_prototype_core_rb/native/extconf.rb"]

  spec.add_dependency "rb_sys", ">= 0.9.130", "< 0.10"
  spec.add_dependency "sorbet-runtime", "~> 0.5"
end
