# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9cc515398b531df3d87635de0e1710edca7a988b9b7d66f475cc32d457df0c0b
# To regenerate: alef generate
# To verify freshness: alef verify
# frozen_string_literal: true

require_relative "structuredmerge_host_prototype/version"
require_relative "structuredmerge_host_prototype/native"

# Top-level namespace for the StructuredmergeHostPrototype Ruby binding.
#
# All type and function symbols are re-exported from the native extension
# loaded via `require_relative "structuredmerge_host_prototype/native"`. See
# {file:README.md} for usage examples and the upstream documentation
# for the full API reference.
module StructuredmergeHostPrototype
  # Re-export all types and functions from native extension
end

# Keep generated types under StructuredmergeHostPrototype. Publishing generated constants
# into Object makes generic names collide with unrelated Ruby libraries.
