# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f3d985dbd69d3ac3a2643bbe62b70a008c2894ae4a795fd4acc54f2044dda5fd
# To regenerate: alef generate
# To verify freshness: alef verify

# frozen_string_literal: true

require "mkmf"
require "rb_sys/mkmf"

default_profile = ENV.fetch("CARGO_PROFILE", "release")

create_rust_makefile("structuredmerge_host_prototype_core_rb") do |config|
  config.profile = default_profile.to_sym
  # extconf.rb and Cargo.toml are siblings under ext/structuredmerge_host_prototype_core_rb/native/; rb_sys interprets
  # ext_dir relative to extconf.rb, so "." finds the sibling Cargo.toml. "native" would
  # resolve to native/native/Cargo.toml and break `gem install` on end-user machines.
  config.ext_dir = "."
end
