// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:3252993871bd56a1c387cb3b368ed6676d077074def252378430992000276cb3
// Re-generate with: alef generate
#![allow(dead_code, unused_imports, unused_variables)]
#![allow(
    clippy::too_many_arguments,
    clippy::let_unit_value,
    clippy::needless_borrow,
    clippy::map_identity,
    clippy::just_underscores_and_digits,
    clippy::unnecessary_cast,
    clippy::unused_unit,
    clippy::unwrap_or_default,
    clippy::derivable_impls,
    clippy::needless_borrows_for_generic_args,
    clippy::unnecessary_fallible_conversions,
    clippy::type_complexity,
    clippy::useless_conversion,
    clippy::clone_on_copy
)]

use async_trait::async_trait;
use magnus::{
    Error, IntoValueFromNative, Ruby, function, method, prelude::*, try_convert::TryConvertOwned,
};
use std::sync::Arc;

/// Run owned Rust work while the calling Ruby thread releases the GVL.
fn alef_magnus_run_without_gvl<F, T>(callback: F) -> T
where
    F: FnOnce() -> T,
{
    struct RunState<F, T> {
        callback: Option<F>,
        result: Option<std::thread::Result<T>>,
    }

    extern "C" fn run_without_gvl<F, T>(data: *mut std::ffi::c_void) -> *mut std::ffi::c_void
    where
        F: FnOnce() -> T,
    {
        // SAFETY: `data` points to the caller's RunState for the duration of this callback.
        let state = unsafe { &mut *(data as *mut RunState<F, T>) };
        let Some(callback) = state.callback.take() else {
            state.result = Some(Err(Box::new("Alef Magnus callback already consumed")));
            return std::ptr::null_mut();
        };
        state.result = Some(std::panic::catch_unwind(std::panic::AssertUnwindSafe(callback)));
        std::ptr::null_mut()
    }

    extern "C" fn unblock_run(_data: *mut std::ffi::c_void) {}

    let mut state = RunState { callback: Some(callback), result: None };
    // SAFETY: Ruby invokes the callback synchronously, and `state` remains live until it returns.
    unsafe {
        rb_sys::rb_thread_call_without_gvl(
            Some(run_without_gvl::<F, T>),
            &mut state as *mut RunState<F, T> as *mut std::ffi::c_void,
            Some(unblock_run),
            std::ptr::null_mut(),
        );
    }

    match state.result.expect("Alef Magnus callback did not run") {
        Ok(result) => result,
        Err(payload) => std::panic::resume_unwind(payload),
    }
}

#[derive(Clone, Debug, serde::Serialize, serde::Deserialize)]
#[magnus::wrap(class = "StructuredmergeHostPrototypeCore::HostBatchRequest")]
pub struct HostBatchRequest {
    schema: String,
    items: Vec<HostSourceSegment>,
}

unsafe impl IntoValueFromNative for HostBatchRequest {}

impl magnus::TryConvert for HostBatchRequest {
    fn try_convert(val: magnus::Value) -> Result<Self, magnus::Error> {
        if let Ok(r) = <&HostBatchRequest as magnus::TryConvert>::try_convert(val) {
            return Ok(r.clone());
        }
        let json_str: String = if let Ok(s) = <String as magnus::TryConvert>::try_convert(val) {
            s
        } else {
            val.funcall::<_, _, String>("to_json", ()).map_err(|e| {
                magnus::Error::new(
                    unsafe { magnus::Ruby::get_unchecked() }.exception_type_error(),
                    format!("no implicit conversion into HostBatchRequest: {}", e),
                )
            })?
        };
        serde_json::from_str::<HostBatchRequest>(&json_str).map_err(|e| {
            magnus::Error::new(
                unsafe { magnus::Ruby::get_unchecked() }.exception_type_error(),
                format!("failed to deserialize HostBatchRequest: {}", e),
            )
        })
    }
}

unsafe impl TryConvertOwned for HostBatchRequest {}

impl HostBatchRequest {
    fn new(args: &[magnus::Value]) -> Result<Self, magnus::Error> {
        let ruby = unsafe { magnus::Ruby::get_unchecked() };
        let args =
            magnus::scan_args::scan_args::<(), (Option<magnus::RHash>,), (), (), (), ()>(args)?;
        let (kwargs_opt,) = args.optional;
        let kwargs = kwargs_opt.unwrap_or_else(|| ruby.hash_new());
        Ok(Self {
            schema: kwargs
                .get(ruby.to_symbol("schema"))
                .and_then(|v| String::try_convert(v).ok())
                .unwrap_or_default(),
            items: kwargs
                .get(ruby.to_symbol("items"))
                .and_then(|v| <Vec<HostSourceSegment>>::try_convert(v).ok())
                .unwrap_or_default(),
        })
    }

    fn schema(&self) -> String {
        self.schema.clone()
    }

    fn items(&self) -> Vec<HostSourceSegment> {
        self.items.clone()
    }
}

#[derive(Clone)]
#[magnus::wrap(class = "StructuredmergeHostPrototypeCore::HostPrototypeError")]
pub struct HostPrototypeError {
    inner: Arc<structuredmerge_host_prototype_core::HostPrototypeError>,
}

unsafe impl IntoValueFromNative for HostPrototypeError {}

impl magnus::TryConvert for HostPrototypeError {
    fn try_convert(val: magnus::Value) -> Result<Self, magnus::Error> {
        let r: &HostPrototypeError = magnus::TryConvert::try_convert(val)?;
        Ok(r.clone())
    }
}

unsafe impl TryConvertOwned for HostPrototypeError {}

impl HostPrototypeError {
    fn message(&self) -> String {
        self.inner.message().into()
    }
}

#[derive(Clone, Debug, serde::Serialize, serde::Deserialize)]
#[magnus::wrap(class = "StructuredmergeHostPrototypeCore::HostSourceSegment")]
pub struct HostSourceSegment {
    source_id: String,
    offset: u64,
    byte_length: u64,
    sha256: String,
}

unsafe impl IntoValueFromNative for HostSourceSegment {}

impl magnus::TryConvert for HostSourceSegment {
    fn try_convert(val: magnus::Value) -> Result<Self, magnus::Error> {
        if let Ok(r) = <&HostSourceSegment as magnus::TryConvert>::try_convert(val) {
            return Ok(r.clone());
        }
        let json_str: String = if let Ok(s) = <String as magnus::TryConvert>::try_convert(val) {
            s
        } else {
            val.funcall::<_, _, String>("to_json", ()).map_err(|e| {
                magnus::Error::new(
                    unsafe { magnus::Ruby::get_unchecked() }.exception_type_error(),
                    format!("no implicit conversion into HostSourceSegment: {}", e),
                )
            })?
        };
        serde_json::from_str::<HostSourceSegment>(&json_str).map_err(|e| {
            magnus::Error::new(
                unsafe { magnus::Ruby::get_unchecked() }.exception_type_error(),
                format!("failed to deserialize HostSourceSegment: {}", e),
            )
        })
    }
}

unsafe impl TryConvertOwned for HostSourceSegment {}

impl HostSourceSegment {
    fn new(args: &[magnus::Value]) -> Result<Self, magnus::Error> {
        let ruby = unsafe { magnus::Ruby::get_unchecked() };
        let args =
            magnus::scan_args::scan_args::<(), (Option<magnus::RHash>,), (), (), (), ()>(args)?;
        let (kwargs_opt,) = args.optional;
        let kwargs = kwargs_opt.unwrap_or_else(|| ruby.hash_new());
        Ok(Self {
            source_id: kwargs
                .get(ruby.to_symbol("source_id"))
                .and_then(|v| String::try_convert(v).ok())
                .unwrap_or_default(),
            offset: kwargs
                .get(ruby.to_symbol("offset"))
                .and_then(|v| u64::try_convert(v).ok())
                .unwrap_or_default(),
            byte_length: kwargs
                .get(ruby.to_symbol("byte_length"))
                .and_then(|v| u64::try_convert(v).ok())
                .unwrap_or_default(),
            sha256: kwargs
                .get(ruby.to_symbol("sha256"))
                .and_then(|v| String::try_convert(v).ok())
                .unwrap_or_default(),
        })
    }

    fn source_id(&self) -> String {
        self.source_id.clone()
    }

    fn offset(&self) -> u64 {
        self.offset
    }

    fn byte_length(&self) -> u64 {
        self.byte_length
    }

    fn sha256(&self) -> String {
        self.sha256.clone()
    }
}

fn cancel_identity_worker(task_id: u64) -> Result<(), Error> {
    let result =
        structuredmerge_host_prototype_core::cancel_identity_worker(task_id).map_err(|e| {
            magnus::Error::new(
                unsafe { Ruby::get_unchecked() }.exception_runtime_error(),
                e.to_string(),
            )
        })?;
    Ok(result)
}

fn dispatch_identity_worker(task_id: u64) -> Result<(), Error> {
    let result =
        structuredmerge_host_prototype_core::dispatch_identity_worker(task_id).map_err(|e| {
            magnus::Error::new(
                unsafe { Ruby::get_unchecked() }.exception_runtime_error(),
                e.to_string(),
            )
        })?;
    Ok(result)
}

fn execute_async_identity(provider_name: String, request: Vec<u8>) -> Result<Vec<u8>, Error> {
    let async_result = alef_magnus_run_without_gvl(move || -> Result<_, String> {
        let rt = tokio::runtime::Builder::new_current_thread()
            .enable_all()
            .build()
            .map_err(|e| e.to_string())?;
        rt.block_on(async {
            structuredmerge_host_prototype_core::execute_async_identity(provider_name, request)
                .await
        })
        .map_err(|e| e.to_string())
    });
    let result = async_result.map_err(|message| {
        magnus::Error::new(unsafe { Ruby::get_unchecked() }.exception_runtime_error(), message)
    })?;
    Ok(result.to_vec())
}

fn execute_async_identity_async(provider_name: String, request: Vec<u8>) -> Result<Vec<u8>, Error> {
    let async_result = alef_magnus_run_without_gvl(move || -> Result<_, String> {
        let rt = tokio::runtime::Builder::new_current_thread()
            .enable_all()
            .build()
            .map_err(|e| e.to_string())?;
        rt.block_on(async {
            structuredmerge_host_prototype_core::execute_async_identity(provider_name, request)
                .await
        })
        .map_err(|e| e.to_string())
    });
    let result = async_result.map_err(|message| {
        magnus::Error::new(unsafe { Ruby::get_unchecked() }.exception_runtime_error(), message)
    })?;
    Ok(result.to_vec())
}

fn execute_detached_identity(
    provider_name: String,
    source_ids: Vec<String>,
    source_lengths: Vec<u64>,
    source_digests: Vec<String>,
    source: Vec<u8>,
) -> Result<Vec<u8>, Error> {
    let result = structuredmerge_host_prototype_core::execute_detached_identity(
        provider_name,
        source_ids,
        source_lengths,
        source_digests,
        source,
    )
    .map_err(|e| {
        magnus::Error::new(
            unsafe { Ruby::get_unchecked() }.exception_runtime_error(),
            e.to_string(),
        )
    })?;
    Ok(result.to_vec())
}

fn execute_identity(provider_name: String, request: Vec<u8>) -> Result<Vec<u8>, Error> {
    let result = structuredmerge_host_prototype_core::execute_identity(provider_name, request)
        .map_err(|e| {
            magnus::Error::new(
                unsafe { Ruby::get_unchecked() }.exception_runtime_error(),
                e.to_string(),
            )
        })?;
    Ok(result.to_vec())
}

fn execute_in_process_identity(
    source_ids: Vec<String>,
    source_lengths: Vec<u64>,
    source_digests: Vec<String>,
    source: Vec<u8>,
) -> Result<Vec<u8>, Error> {
    let result = structuredmerge_host_prototype_core::execute_in_process_identity(
        source_ids,
        source_lengths,
        source_digests,
        source,
    )
    .map_err(|e| {
        magnus::Error::new(
            unsafe { Ruby::get_unchecked() }.exception_runtime_error(),
            e.to_string(),
        )
    })?;
    Ok(result.to_vec())
}

fn execute_typed_identity(
    provider_name: String,
    source_ids: Vec<String>,
    source_lengths: Vec<u64>,
    source_digests: Vec<String>,
    source: Vec<u8>,
) -> Result<Vec<u8>, Error> {
    let result = structuredmerge_host_prototype_core::execute_typed_identity(
        provider_name,
        source_ids,
        source_lengths,
        source_digests,
        source,
    )
    .map_err(|e| {
        magnus::Error::new(
            unsafe { Ruby::get_unchecked() }.exception_runtime_error(),
            e.to_string(),
        )
    })?;
    Ok(result.to_vec())
}

fn execute_typed_workflow(
    provider_name: String,
    source_ids: Vec<String>,
    source_lengths: Vec<u64>,
    source_digests: Vec<String>,
    source: Vec<u8>,
) -> Result<Vec<u8>, Error> {
    let result = structuredmerge_host_prototype_core::execute_typed_workflow(
        provider_name,
        source_ids,
        source_lengths,
        source_digests,
        source,
    )
    .map_err(|e| {
        magnus::Error::new(
            unsafe { Ruby::get_unchecked() }.exception_runtime_error(),
            e.to_string(),
        )
    })?;
    Ok(result.to_vec())
}

fn identity_worker_cancelled(task_id: u64) -> Result<bool, Error> {
    let result =
        structuredmerge_host_prototype_core::identity_worker_cancelled(task_id).map_err(|e| {
            magnus::Error::new(
                unsafe { Ruby::get_unchecked() }.exception_runtime_error(),
                e.to_string(),
            )
        })?;
    Ok(result)
}

fn merge_json_three_way(
    base_source: String,
    ours_source: String,
    theirs_source: String,
    dialect: String,
) -> Result<String, Error> {
    let result = structuredmerge_host_prototype_core::merge_json_three_way(
        base_source,
        ours_source,
        theirs_source,
        dialect,
    )
    .map_err(|e| {
        magnus::Error::new(
            unsafe { Ruby::get_unchecked() }.exception_runtime_error(),
            e.to_string(),
        )
    })?;
    Ok(result)
}

fn merge_json_two_way(
    incoming_source: String,
    current_source: String,
    dialect: String,
) -> Result<String, Error> {
    let result = structuredmerge_host_prototype_core::merge_json_two_way(
        incoming_source,
        current_source,
        dialect,
    )
    .map_err(|e| {
        magnus::Error::new(
            unsafe { Ruby::get_unchecked() }.exception_runtime_error(),
            e.to_string(),
        )
    })?;
    Ok(result)
}

fn parse_with_parser(provider_name: String, request: Vec<u8>) -> Result<Vec<u8>, Error> {
    let result = structuredmerge_host_prototype_core::parse_with_parser(provider_name, request)
        .map_err(|e| {
            magnus::Error::new(
                unsafe { Ruby::get_unchecked() }.exception_runtime_error(),
                e.to_string(),
            )
        })?;
    Ok(result.to_vec())
}

fn poll_identity_worker(task_id: u64) -> Result<Option<Vec<u8>>, Error> {
    let result =
        structuredmerge_host_prototype_core::poll_identity_worker(task_id).map_err(|e| {
            magnus::Error::new(
                unsafe { Ruby::get_unchecked() }.exception_runtime_error(),
                e.to_string(),
            )
        })?;
    Ok(result)
}

fn prepare_identity_worker(provider_name: String, request: Vec<u8>) -> Result<u64, Error> {
    let result =
        structuredmerge_host_prototype_core::prepare_identity_worker(provider_name, request)
            .map_err(|e| {
                magnus::Error::new(
                    unsafe { Ruby::get_unchecked() }.exception_runtime_error(),
                    e.to_string(),
                )
            })?;
    Ok(result)
}

fn probe_with_parser(provider_name: String, request: Vec<u8>) -> Result<Vec<u8>, Error> {
    let result = structuredmerge_host_prototype_core::probe_with_parser(provider_name, request)
        .map_err(|e| {
            magnus::Error::new(
                unsafe { Ruby::get_unchecked() }.exception_runtime_error(),
                e.to_string(),
            )
        })?;
    Ok(result.to_vec())
}

fn register_tslp_parser_host(provider_name: String, language: String) -> Result<(), Error> {
    let result =
        structuredmerge_host_prototype_core::register_tslp_parser_host(provider_name, language)
            .map_err(|e| {
                magnus::Error::new(
                    unsafe { Ruby::get_unchecked() }.exception_runtime_error(),
                    e.to_string(),
                )
            })?;
    Ok(result)
}

fn registered_parser_hosts() -> Vec<String> {
    structuredmerge_host_prototype_core::registered_parser_hosts()
}

fn registered_workflow_hosts() -> Vec<String> {
    structuredmerge_host_prototype_core::registered_workflow_hosts()
}

#[allow(clippy::missing_errors_doc)]
#[allow(unused_variables)]
pub fn replace_parser_host(provider: magnus::Value, name: String) -> Result<(), Error> {
    let provider = {
        let bridge = RbParserHostBridge::new(provider, name.clone())?;
        std::sync::Arc::new(bridge)
            as std::sync::Arc<dyn structuredmerge_host_prototype_core::ParserHost>
    };
    structuredmerge_host_prototype_core::replace_parser_host(provider, name).map_err(|e| {
        magnus::Error::new(
            unsafe { magnus::Ruby::get_unchecked() }.exception_runtime_error(),
            e.to_string(),
        )
    })
}

#[allow(clippy::missing_errors_doc)]
#[allow(unused_variables)]
pub fn replace_workflow_host(provider: magnus::Value, name: String) -> Result<(), Error> {
    let provider = {
        let bridge = RbWorkflowHostBridge::new(provider, name.clone())?;
        std::sync::Arc::new(bridge)
            as std::sync::Arc<dyn structuredmerge_host_prototype_core::WorkflowHost>
    };
    structuredmerge_host_prototype_core::replace_workflow_host(provider, name).map_err(|e| {
        magnus::Error::new(
            unsafe { magnus::Ruby::get_unchecked() }.exception_runtime_error(),
            e.to_string(),
        )
    })
}

fn shutdown_host_runtime(timeout_millis: u64, force: bool) -> Result<Vec<u64>, Error> {
    let async_result = alef_magnus_run_without_gvl(move || -> Result<_, String> {
        let rt = tokio::runtime::Builder::new_current_thread()
            .enable_all()
            .build()
            .map_err(|e| e.to_string())?;
        rt.block_on(async {
            structuredmerge_host_prototype_core::shutdown_host_runtime(timeout_millis, force).await
        })
        .map_err(|e| e.to_string())
    });
    let result = async_result.map_err(|message| {
        magnus::Error::new(unsafe { Ruby::get_unchecked() }.exception_runtime_error(), message)
    })?;
    Ok(result)
}

fn shutdown_host_runtime_async(timeout_millis: u64, force: bool) -> Result<Vec<u64>, Error> {
    let async_result = alef_magnus_run_without_gvl(move || -> Result<_, String> {
        let rt = tokio::runtime::Builder::new_current_thread()
            .enable_all()
            .build()
            .map_err(|e| e.to_string())?;
        rt.block_on(async {
            structuredmerge_host_prototype_core::shutdown_host_runtime(timeout_millis, force).await
        })
        .map_err(|e| e.to_string())
    });
    let result = async_result.map_err(|message| {
        magnus::Error::new(unsafe { Ruby::get_unchecked() }.exception_runtime_error(), message)
    })?;
    Ok(result)
}

fn start_host_runtime() -> Result<(), Error> {
    let result = structuredmerge_host_prototype_core::start_host_runtime().map_err(|e| {
        magnus::Error::new(
            unsafe { Ruby::get_unchecked() }.exception_runtime_error(),
            e.to_string(),
        )
    })?;
    Ok(result)
}

fn start_identity_worker(provider_name: String, request: Vec<u8>) -> Result<u64, Error> {
    let result = structuredmerge_host_prototype_core::start_identity_worker(provider_name, request)
        .map_err(|e| {
            magnus::Error::new(
                unsafe { Ruby::get_unchecked() }.exception_runtime_error(),
                e.to_string(),
            )
        })?;
    Ok(result)
}

#[allow(unused_imports)]
use magnus::TryConvert as _;
#[allow(unused_imports)]
use magnus::value::InnerValue as _;
type RbWorkflowHostBridgeRuntimeJob =
    Box<dyn FnOnce(&magnus::Ruby, magnus::Value) + Send + 'static>;

#[derive(Clone)]
struct RbWorkflowHostBridgeRuntimeDispatcher {
    sender: std::sync::mpsc::SyncSender<RbWorkflowHostBridgeRuntimeJob>,
}

impl RbWorkflowHostBridgeRuntimeDispatcher {
    const QUEUE_CAPACITY: usize = 64;

    fn new(ruby: &magnus::Ruby, rb_obj: magnus::Value) -> Result<Self, magnus::Error> {
        use magnus::value::InnerValue as _;

        let (sender, receiver) = std::sync::mpsc::sync_channel(Self::QUEUE_CAPACITY);
        let inner = magnus::value::Opaque::from(rb_obj);
        let thread = ruby.thread_create_from_fn(move |ruby| {
            while let Ok(job) = Self::recv_without_gvl(&receiver) {
                let value = inner.get_inner_with(ruby);
                let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
                    job(ruby, value);
                }));
            }
        });

        // The active Ruby thread is VM-rooted; its ivar keeps the host object live
        // until every bridge sender is gone and the dispatcher exits.
        use magnus::Object as _;
        thread.ivar_set("__alef_trait_bridge_host", rb_obj)?;
        Ok(Self { sender })
    }

    fn dispatch<T, F>(&self, callback: F) -> Result<T, String>
    where
        T: Send + 'static,
        F: FnOnce(&magnus::Ruby, magnus::Value) -> T + Send + 'static,
    {
        let (result_sender, result_receiver) = std::sync::mpsc::sync_channel(1);
        self.sender
            .send(Box::new(move |ruby, value| {
                let result = callback(ruby, value);
                let _ = result_sender.send(result);
            }))
            .map_err(|_| "Ruby runtime dispatcher is not available".to_string())?;
        result_receiver
            .recv()
            .map_err(|_| "Ruby runtime dispatcher callback did not return".to_string())
    }

    fn recv_without_gvl(
        receiver: &std::sync::mpsc::Receiver<RbWorkflowHostBridgeRuntimeJob>,
    ) -> Result<RbWorkflowHostBridgeRuntimeJob, std::sync::mpsc::RecvError> {
        struct ReceiveState<'a> {
            receiver: &'a std::sync::mpsc::Receiver<RbWorkflowHostBridgeRuntimeJob>,
            result: Option<Result<RbWorkflowHostBridgeRuntimeJob, std::sync::mpsc::RecvError>>,
        }

        unsafe extern "C" fn receive(data: *mut std::ffi::c_void) -> *mut std::ffi::c_void {
            // SAFETY: the state pointer remains valid until Ruby returns from the
            // without-GVL callback on this same Ruby-created thread.
            let state = unsafe { &mut *(data as *mut ReceiveState<'_>) };
            state.result = Some(state.receiver.recv());
            std::ptr::null_mut()
        }

        let mut state = ReceiveState { receiver, result: None };
        // SAFETY: this runs on the dedicated Ruby-created dispatcher thread. The
        // callback touches only Rust channel state and the sender disconnect wakes it.
        unsafe {
            rb_sys::rb_thread_call_without_gvl(
                Some(receive),
                &mut state as *mut ReceiveState<'_> as *mut std::ffi::c_void,
                None,
                std::ptr::null_mut(),
            );
        }
        state.result.unwrap_or_else(|| Err(std::sync::mpsc::RecvError))
    }
}

/// Wrapper that bridges a foreign Rb object to the `WorkflowHost` trait.
pub struct RbWorkflowHostBridge {
    inner: magnus::value::Opaque<magnus::Value>,
    cached_name: String,
    has_initialize: bool,
    has_shutdown: bool,
    runtime_dispatcher: RbWorkflowHostBridgeRuntimeDispatcher,
}

impl std::fmt::Debug for RbWorkflowHostBridge {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "RbWorkflowHostBridge")
    }
}

impl RbWorkflowHostBridge {
    /// Create a new bridge wrapping a Ruby object.
    /// Validates that the Ruby object responds to all required methods.
    pub fn new(rb_obj: magnus::Value, name: String) -> Result<Self, magnus::Error> {
        // SAFETY: constructors are called by generated Magnus registration functions.
        let ruby = unsafe { magnus::Ruby::get_unchecked() };
        if !rb_obj.respond_to("descriptor", false).unwrap_or(false) {
            let ruby = unsafe { magnus::Ruby::get_unchecked() };
            return Err(magnus::Error::new(
                ruby.exception_runtime_error(),
                format!("Ruby object missing required method: {}", "descriptor"),
            ));
        }
        if !rb_obj.respond_to("execute_batch", false).unwrap_or(false) {
            let ruby = unsafe { magnus::Ruby::get_unchecked() };
            return Err(magnus::Error::new(
                ruby.exception_runtime_error(),
                format!("Ruby object missing required method: {}", "execute_batch"),
            ));
        }
        if !rb_obj.respond_to("execute_cancellable_batch", false).unwrap_or(false) {
            let ruby = unsafe { magnus::Ruby::get_unchecked() };
            return Err(magnus::Error::new(
                ruby.exception_runtime_error(),
                format!("Ruby object missing required method: {}", "execute_cancellable_batch"),
            ));
        }
        if !rb_obj.respond_to("execute_async_batch", false).unwrap_or(false) {
            let ruby = unsafe { magnus::Ruby::get_unchecked() };
            return Err(magnus::Error::new(
                ruby.exception_runtime_error(),
                format!("Ruby object missing required method: {}", "execute_async_batch"),
            ));
        }
        if !rb_obj.respond_to("execute_typed_batch", false).unwrap_or(false) {
            let ruby = unsafe { magnus::Ruby::get_unchecked() };
            return Err(magnus::Error::new(
                ruby.exception_runtime_error(),
                format!("Ruby object missing required method: {}", "execute_typed_batch"),
            ));
        }
        if !rb_obj.respond_to("execute_detached_batch", false).unwrap_or(false) {
            let ruby = unsafe { magnus::Ruby::get_unchecked() };
            return Err(magnus::Error::new(
                ruby.exception_runtime_error(),
                format!("Ruby object missing required method: {}", "execute_detached_batch"),
            ));
        }
        let runtime_dispatcher = RbWorkflowHostBridgeRuntimeDispatcher::new(&ruby, rb_obj)?;

        Ok(Self {
            inner: magnus::value::Opaque::from(rb_obj),
            cached_name: name,
            runtime_dispatcher,
            has_initialize: rb_obj.respond_to("initialize", false).unwrap_or(false),
            has_shutdown: rb_obj.respond_to("shutdown", false).unwrap_or(false),
        })
    }
}

impl structuredmerge_host_prototype_core::Plugin for RbWorkflowHostBridge {
    fn name(&self) -> &str {
        &self.cached_name
    }

    fn version(
        &self,
    ) -> std::result::Result<String, structuredmerge_host_prototype_core::HostPrototypeError> {
        let callback = move |ruby: &magnus::Ruby,
                             value: magnus::Value|
              -> std::result::Result<
            String,
            structuredmerge_host_prototype_core::HostPrototypeError,
        > {
            let val: magnus::Value = match value.funcall::<_, _, magnus::Value>("version", ()) {
                Ok(v) => v,
                Err(e) => {
                    return Err(structuredmerge_host_prototype_core::HostPrototypeError::new(
                        format!("Ruby method 'version' failed: {}", e),
                    ));
                }
            };
            <String as magnus::TryConvert>::try_convert(val).map_err(|e| {
                structuredmerge_host_prototype_core::HostPrototypeError::new(format!(
                    "Failed to convert Ruby 'version' return value: {}",
                    e
                ))
            })
        };
        match magnus::Ruby::get() {
            Ok(ruby) => callback(&ruby, self.inner.get_inner_with(&ruby)),
            Err(_) => match self.runtime_dispatcher.dispatch(callback) {
                Ok(result) => result,
                Err(error) => Err(structuredmerge_host_prototype_core::HostPrototypeError::new(
                    format!("Ruby runtime dispatcher failed for method 'version': {}", error),
                )),
            },
        }
    }

    fn initialize(
        &self,
    ) -> std::result::Result<(), structuredmerge_host_prototype_core::HostPrototypeError> {
        if !(self.has_initialize) {
            return Ok(());
        }
        let callback = move |ruby: &magnus::Ruby,
                             value: magnus::Value|
              -> std::result::Result<
            (),
            structuredmerge_host_prototype_core::HostPrototypeError,
        > {
            let val: magnus::Value = match value.funcall::<_, _, magnus::Value>("initialize", ()) {
                Ok(v) => v,
                Err(e) => {
                    return Err(structuredmerge_host_prototype_core::HostPrototypeError::new(
                        format!("Ruby method 'initialize' failed: {}", e),
                    ));
                }
            };
            let _ = val;
            Ok(())
        };
        match magnus::Ruby::get() {
            Ok(ruby) => callback(&ruby, self.inner.get_inner_with(&ruby)),
            Err(_) => match self.runtime_dispatcher.dispatch(callback) {
                Ok(result) => result,
                Err(error) => Err(structuredmerge_host_prototype_core::HostPrototypeError::new(
                    format!("Ruby runtime dispatcher failed for method 'initialize': {}", error),
                )),
            },
        }
    }

    fn shutdown(
        &self,
    ) -> std::result::Result<(), structuredmerge_host_prototype_core::HostPrototypeError> {
        if !(self.has_shutdown) {
            return Ok(());
        }
        let callback = move |ruby: &magnus::Ruby,
                             value: magnus::Value|
              -> std::result::Result<
            (),
            structuredmerge_host_prototype_core::HostPrototypeError,
        > {
            let val: magnus::Value = match value.funcall::<_, _, magnus::Value>("shutdown", ()) {
                Ok(v) => v,
                Err(e) => {
                    return Err(structuredmerge_host_prototype_core::HostPrototypeError::new(
                        format!("Ruby method 'shutdown' failed: {}", e),
                    ));
                }
            };
            let _ = val;
            Ok(())
        };
        match magnus::Ruby::get() {
            Ok(ruby) => callback(&ruby, self.inner.get_inner_with(&ruby)),
            Err(_) => match self.runtime_dispatcher.dispatch(callback) {
                Ok(result) => result,
                Err(error) => Err(structuredmerge_host_prototype_core::HostPrototypeError::new(
                    format!("Ruby runtime dispatcher failed for method 'shutdown': {}", error),
                )),
            },
        }
    }
}

#[async_trait::async_trait]
impl structuredmerge_host_prototype_core::WorkflowHost for RbWorkflowHostBridge {
    fn descriptor(
        &self,
    ) -> std::result::Result<String, structuredmerge_host_prototype_core::HostPrototypeError> {
        let callback = move |ruby: &magnus::Ruby,
                             value: magnus::Value|
              -> std::result::Result<
            String,
            structuredmerge_host_prototype_core::HostPrototypeError,
        > {
            let val: magnus::Value = match value.funcall::<_, _, magnus::Value>("descriptor", ()) {
                Ok(v) => v,
                Err(e) => {
                    return Err(structuredmerge_host_prototype_core::HostPrototypeError::new(
                        format!("Ruby method 'descriptor' failed: {}", e),
                    ));
                }
            };
            <String as magnus::TryConvert>::try_convert(val).map_err(|e| {
                structuredmerge_host_prototype_core::HostPrototypeError::new(format!(
                    "Failed to convert Ruby 'descriptor' return value: {}",
                    e
                ))
            })
        };
        match magnus::Ruby::get() {
            Ok(ruby) => callback(&ruby, self.inner.get_inner_with(&ruby)),
            Err(_) => match self.runtime_dispatcher.dispatch(callback) {
                Ok(result) => result,
                Err(error) => Err(structuredmerge_host_prototype_core::HostPrototypeError::new(
                    format!("Ruby runtime dispatcher failed for method 'descriptor': {}", error),
                )),
            },
        }
    }

    fn execute_batch(
        &self,
        request: Vec<u8>,
    ) -> std::result::Result<Vec<u8>, structuredmerge_host_prototype_core::HostPrototypeError> {
        let request_owned = request;
        let callback = move |ruby: &magnus::Ruby,
                             value: magnus::Value|
              -> std::result::Result<
            Vec<u8>,
            structuredmerge_host_prototype_core::HostPrototypeError,
        > {
            let val: magnus::Value = match value.funcall::<_, _, magnus::Value>(
                "execute_batch",
                (ruby.str_from_slice(AsRef::<[u8]>::as_ref(&request_owned)).as_value(),),
            ) {
                Ok(v) => v,
                Err(e) => {
                    return Err(structuredmerge_host_prototype_core::HostPrototypeError::new(
                        format!("Ruby method 'execute_batch' failed: {}", e),
                    ));
                }
            };
            <magnus::RString as magnus::TryConvert>::try_convert(val)
                .map(|bytes| unsafe { bytes.as_slice() }.to_vec())
                .map_err(|e| {
                    structuredmerge_host_prototype_core::HostPrototypeError::new(format!(
                        "Failed to convert Ruby 'execute_batch' return value: {}",
                        e
                    ))
                })
        };
        match magnus::Ruby::get() {
            Ok(ruby) => callback(&ruby, self.inner.get_inner_with(&ruby)),
            Err(_) => match self.runtime_dispatcher.dispatch(callback) {
                Ok(result) => result,
                Err(error) => Err(structuredmerge_host_prototype_core::HostPrototypeError::new(
                    format!("Ruby runtime dispatcher failed for method 'execute_batch': {}", error),
                )),
            },
        }
    }

    fn execute_cancellable_batch(
        &self,
        task_id: u64,
        request: Vec<u8>,
    ) -> std::result::Result<Vec<u8>, structuredmerge_host_prototype_core::HostPrototypeError> {
        let task_id_owned = task_id;
        let request_owned = request;
        let callback = move |ruby: &magnus::Ruby,
                             value: magnus::Value|
              -> std::result::Result<
            Vec<u8>,
            structuredmerge_host_prototype_core::HostPrototypeError,
        > {
            let val: magnus::Value = match value.funcall::<_, _, magnus::Value>(
                "execute_cancellable_batch",
                (
                    task_id_owned,
                    ruby.str_from_slice(AsRef::<[u8]>::as_ref(&request_owned)).as_value(),
                ),
            ) {
                Ok(v) => v,
                Err(e) => {
                    return Err(structuredmerge_host_prototype_core::HostPrototypeError::new(
                        format!("Ruby method 'execute_cancellable_batch' failed: {}", e),
                    ));
                }
            };
            <magnus::RString as magnus::TryConvert>::try_convert(val)
                .map(|bytes| unsafe { bytes.as_slice() }.to_vec())
                .map_err(|e| {
                    structuredmerge_host_prototype_core::HostPrototypeError::new(format!(
                        "Failed to convert Ruby 'execute_cancellable_batch' return value: {}",
                        e
                    ))
                })
        };
        match magnus::Ruby::get() {
            Ok(ruby) => callback(&ruby, self.inner.get_inner_with(&ruby)),
            Err(_) => match self.runtime_dispatcher.dispatch(callback) {
                Ok(result) => result,
                Err(error) => {
                    Err(structuredmerge_host_prototype_core::HostPrototypeError::new(format!(
                        "Ruby runtime dispatcher failed for method 'execute_cancellable_batch': {}",
                        error
                    )))
                }
            },
        }
    }

    async fn execute_async_batch(
        &self,
        request: Vec<u8>,
    ) -> std::result::Result<Vec<u8>, structuredmerge_host_prototype_core::HostPrototypeError> {
        let request_owned = request;
        let dispatcher = self.runtime_dispatcher.clone();
        let callback = move |ruby: &magnus::Ruby,
                             value: magnus::Value|
              -> std::result::Result<
            Vec<u8>,
            structuredmerge_host_prototype_core::HostPrototypeError,
        > {
            let val: magnus::Value = match value.funcall::<_, _, magnus::Value>(
                "execute_async_batch",
                (ruby.str_from_slice(AsRef::<[u8]>::as_ref(&request_owned)).as_value(),),
            ) {
                Ok(v) => v,
                Err(e) => {
                    return Err(structuredmerge_host_prototype_core::HostPrototypeError::new(
                        format!("Ruby method 'execute_async_batch' failed: {}", e),
                    ));
                }
            };
            <magnus::RString as magnus::TryConvert>::try_convert(val)
                .map(|bytes| unsafe { bytes.as_slice() }.to_vec())
                .map_err(|e| {
                    structuredmerge_host_prototype_core::HostPrototypeError::new(format!(
                        "Failed to convert Ruby 'execute_async_batch' return value: {}",
                        e
                    ))
                })
        };
        match tokio::task::spawn_blocking(move || dispatcher.dispatch(callback)).await {
            Ok(Ok(result)) => result,
            Ok(Err(error)) => {
                Err(structuredmerge_host_prototype_core::HostPrototypeError::new(format!(
                    "Ruby runtime dispatcher failed for method 'execute_async_batch': {}",
                    error
                )))
            }
            Err(error) => {
                Err(structuredmerge_host_prototype_core::HostPrototypeError::new(format!(
                    "Ruby runtime dispatcher task failed for method 'execute_async_batch': {}",
                    error
                )))
            }
        }
    }

    fn execute_typed_batch(
        &self,
        request: structuredmerge_host_prototype_core::HostBatchRequest,
        source: Vec<u8>,
    ) -> std::result::Result<Vec<u8>, structuredmerge_host_prototype_core::HostPrototypeError> {
        let request_owned = request;
        let source_owned = source;
        let callback = move |ruby: &magnus::Ruby,
                             value: magnus::Value|
              -> std::result::Result<
            Vec<u8>,
            structuredmerge_host_prototype_core::HostPrototypeError,
        > {
            let val: magnus::Value = match value.funcall::<_, _, magnus::Value>(
                "execute_typed_batch",
                (
                    {
                        use magnus::IntoValue;
                        HostBatchRequest::from(request_owned.clone()).into_value_with(ruby)
                    },
                    ruby.str_from_slice(AsRef::<[u8]>::as_ref(&source_owned)).as_value(),
                ),
            ) {
                Ok(v) => v,
                Err(e) => {
                    return Err(structuredmerge_host_prototype_core::HostPrototypeError::new(
                        format!("Ruby method 'execute_typed_batch' failed: {}", e),
                    ));
                }
            };
            <magnus::RString as magnus::TryConvert>::try_convert(val)
                .map(|bytes| unsafe { bytes.as_slice() }.to_vec())
                .map_err(|e| {
                    structuredmerge_host_prototype_core::HostPrototypeError::new(format!(
                        "Failed to convert Ruby 'execute_typed_batch' return value: {}",
                        e
                    ))
                })
        };
        match magnus::Ruby::get() {
            Ok(ruby) => callback(&ruby, self.inner.get_inner_with(&ruby)),
            Err(_) => match self.runtime_dispatcher.dispatch(callback) {
                Ok(result) => result,
                Err(error) => {
                    Err(structuredmerge_host_prototype_core::HostPrototypeError::new(format!(
                        "Ruby runtime dispatcher failed for method 'execute_typed_batch': {}",
                        error
                    )))
                }
            },
        }
    }

    fn execute_detached_batch(
        &self,
        request: Vec<u8>,
    ) -> std::result::Result<Vec<u8>, structuredmerge_host_prototype_core::HostPrototypeError> {
        let request_owned = request;
        let callback = move |ruby: &magnus::Ruby,
                             value: magnus::Value|
              -> std::result::Result<
            Vec<u8>,
            structuredmerge_host_prototype_core::HostPrototypeError,
        > {
            let val: magnus::Value = match value.funcall::<_, _, magnus::Value>(
                "execute_detached_batch",
                (ruby.str_from_slice(AsRef::<[u8]>::as_ref(&request_owned)).as_value(),),
            ) {
                Ok(v) => v,
                Err(e) => {
                    return Err(structuredmerge_host_prototype_core::HostPrototypeError::new(
                        format!("Ruby method 'execute_detached_batch' failed: {}", e),
                    ));
                }
            };
            <magnus::RString as magnus::TryConvert>::try_convert(val)
                .map(|bytes| unsafe { bytes.as_slice() }.to_vec())
                .map_err(|e| {
                    structuredmerge_host_prototype_core::HostPrototypeError::new(format!(
                        "Failed to convert Ruby 'execute_detached_batch' return value: {}",
                        e
                    ))
                })
        };
        match magnus::Ruby::get() {
            Ok(ruby) => callback(&ruby, self.inner.get_inner_with(&ruby)),
            Err(_) => match self.runtime_dispatcher.dispatch(callback) {
                Ok(result) => result,
                Err(error) => {
                    Err(structuredmerge_host_prototype_core::HostPrototypeError::new(format!(
                        "Ruby runtime dispatcher failed for method 'execute_detached_batch': {}",
                        error
                    )))
                }
            },
        }
    }
}

pub fn register_workflow_host(rb_obj: magnus::Value, name: String) -> Result<(), magnus::Error> {
    let required_methods = [
        "descriptor",
        "execute_batch",
        "execute_cancellable_batch",
        "execute_async_batch",
        "execute_typed_batch",
        "execute_detached_batch",
    ];
    for method in &required_methods {
        if !rb_obj.respond_to(*method, false).unwrap_or(false) {
            let ruby = unsafe { magnus::Ruby::get_unchecked() };
            return Err(magnus::Error::new(
                ruby.exception_runtime_error(),
                format!("Backend missing required method: {}", method),
            ));
        }
    }
    let wrapper = RbWorkflowHostBridge::new(rb_obj, name)?;
    let arc: Arc<dyn structuredmerge_host_prototype_core::WorkflowHost> = Arc::new(wrapper);

    structuredmerge_host_prototype_core::plugins::register_workflow_host(arc).map_err(|e| {
        let ruby = unsafe { magnus::Ruby::get_unchecked() };
        magnus::Error::new(ruby.exception_runtime_error(), format!("register failed: {}", e))
    })?;
    Ok(())
}

pub fn unregister_workflow_host(name: String) -> Result<(), magnus::Error> {
    structuredmerge_host_prototype_core::plugins::unregister_workflow_host(&name).map_err(|e| {
        let ruby = unsafe { magnus::Ruby::get_unchecked() };
        magnus::Error::new(ruby.exception_runtime_error(), format!("{}", e))
    })
}

pub fn clear_workflow_hosts() -> Result<(), magnus::Error> {
    structuredmerge_host_prototype_core::plugins::clear_workflow_hosts().map_err(|e| {
        let ruby = unsafe { magnus::Ruby::get_unchecked() };
        magnus::Error::new(ruby.exception_runtime_error(), format!("{}", e))
    })
}

#[allow(unused_imports)]
use magnus::TryConvert as _;
#[allow(unused_imports)]
use magnus::value::InnerValue as _;
type RbParserHostBridgeRuntimeJob = Box<dyn FnOnce(&magnus::Ruby, magnus::Value) + Send + 'static>;

#[derive(Clone)]
struct RbParserHostBridgeRuntimeDispatcher {
    sender: std::sync::mpsc::SyncSender<RbParserHostBridgeRuntimeJob>,
}

impl RbParserHostBridgeRuntimeDispatcher {
    const QUEUE_CAPACITY: usize = 64;

    fn new(ruby: &magnus::Ruby, rb_obj: magnus::Value) -> Result<Self, magnus::Error> {
        use magnus::value::InnerValue as _;

        let (sender, receiver) = std::sync::mpsc::sync_channel(Self::QUEUE_CAPACITY);
        let inner = magnus::value::Opaque::from(rb_obj);
        let thread = ruby.thread_create_from_fn(move |ruby| {
            while let Ok(job) = Self::recv_without_gvl(&receiver) {
                let value = inner.get_inner_with(ruby);
                let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
                    job(ruby, value);
                }));
            }
        });

        // The active Ruby thread is VM-rooted; its ivar keeps the host object live
        // until every bridge sender is gone and the dispatcher exits.
        use magnus::Object as _;
        thread.ivar_set("__alef_trait_bridge_host", rb_obj)?;
        Ok(Self { sender })
    }

    fn dispatch<T, F>(&self, callback: F) -> Result<T, String>
    where
        T: Send + 'static,
        F: FnOnce(&magnus::Ruby, magnus::Value) -> T + Send + 'static,
    {
        let (result_sender, result_receiver) = std::sync::mpsc::sync_channel(1);
        self.sender
            .send(Box::new(move |ruby, value| {
                let result = callback(ruby, value);
                let _ = result_sender.send(result);
            }))
            .map_err(|_| "Ruby runtime dispatcher is not available".to_string())?;
        result_receiver
            .recv()
            .map_err(|_| "Ruby runtime dispatcher callback did not return".to_string())
    }

    fn recv_without_gvl(
        receiver: &std::sync::mpsc::Receiver<RbParserHostBridgeRuntimeJob>,
    ) -> Result<RbParserHostBridgeRuntimeJob, std::sync::mpsc::RecvError> {
        struct ReceiveState<'a> {
            receiver: &'a std::sync::mpsc::Receiver<RbParserHostBridgeRuntimeJob>,
            result: Option<Result<RbParserHostBridgeRuntimeJob, std::sync::mpsc::RecvError>>,
        }

        unsafe extern "C" fn receive(data: *mut std::ffi::c_void) -> *mut std::ffi::c_void {
            // SAFETY: the state pointer remains valid until Ruby returns from the
            // without-GVL callback on this same Ruby-created thread.
            let state = unsafe { &mut *(data as *mut ReceiveState<'_>) };
            state.result = Some(state.receiver.recv());
            std::ptr::null_mut()
        }

        let mut state = ReceiveState { receiver, result: None };
        // SAFETY: this runs on the dedicated Ruby-created dispatcher thread. The
        // callback touches only Rust channel state and the sender disconnect wakes it.
        unsafe {
            rb_sys::rb_thread_call_without_gvl(
                Some(receive),
                &mut state as *mut ReceiveState<'_> as *mut std::ffi::c_void,
                None,
                std::ptr::null_mut(),
            );
        }
        state.result.unwrap_or_else(|| Err(std::sync::mpsc::RecvError))
    }
}

/// Wrapper that bridges a foreign Rb object to the `ParserHost` trait.
pub struct RbParserHostBridge {
    inner: magnus::value::Opaque<magnus::Value>,
    cached_name: String,
    has_initialize: bool,
    has_shutdown: bool,
    runtime_dispatcher: RbParserHostBridgeRuntimeDispatcher,
}

impl std::fmt::Debug for RbParserHostBridge {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "RbParserHostBridge")
    }
}

impl RbParserHostBridge {
    /// Create a new bridge wrapping a Ruby object.
    /// Validates that the Ruby object responds to all required methods.
    pub fn new(rb_obj: magnus::Value, name: String) -> Result<Self, magnus::Error> {
        // SAFETY: constructors are called by generated Magnus registration functions.
        let ruby = unsafe { magnus::Ruby::get_unchecked() };
        if !rb_obj.respond_to("descriptor", false).unwrap_or(false) {
            let ruby = unsafe { magnus::Ruby::get_unchecked() };
            return Err(magnus::Error::new(
                ruby.exception_runtime_error(),
                format!("Ruby object missing required method: {}", "descriptor"),
            ));
        }
        if !rb_obj.respond_to("probe_batch", false).unwrap_or(false) {
            let ruby = unsafe { magnus::Ruby::get_unchecked() };
            return Err(magnus::Error::new(
                ruby.exception_runtime_error(),
                format!("Ruby object missing required method: {}", "probe_batch"),
            ));
        }
        if !rb_obj.respond_to("parse_batch", false).unwrap_or(false) {
            let ruby = unsafe { magnus::Ruby::get_unchecked() };
            return Err(magnus::Error::new(
                ruby.exception_runtime_error(),
                format!("Ruby object missing required method: {}", "parse_batch"),
            ));
        }
        let runtime_dispatcher = RbParserHostBridgeRuntimeDispatcher::new(&ruby, rb_obj)?;

        Ok(Self {
            inner: magnus::value::Opaque::from(rb_obj),
            cached_name: name,
            runtime_dispatcher,
            has_initialize: rb_obj.respond_to("initialize", false).unwrap_or(false),
            has_shutdown: rb_obj.respond_to("shutdown", false).unwrap_or(false),
        })
    }
}

impl structuredmerge_host_prototype_core::Plugin for RbParserHostBridge {
    fn name(&self) -> &str {
        &self.cached_name
    }

    fn version(
        &self,
    ) -> std::result::Result<String, structuredmerge_host_prototype_core::HostPrototypeError> {
        let callback = move |ruby: &magnus::Ruby,
                             value: magnus::Value|
              -> std::result::Result<
            String,
            structuredmerge_host_prototype_core::HostPrototypeError,
        > {
            let val: magnus::Value = match value.funcall::<_, _, magnus::Value>("version", ()) {
                Ok(v) => v,
                Err(e) => {
                    return Err(structuredmerge_host_prototype_core::HostPrototypeError::new(
                        format!("Ruby method 'version' failed: {}", e),
                    ));
                }
            };
            <String as magnus::TryConvert>::try_convert(val).map_err(|e| {
                structuredmerge_host_prototype_core::HostPrototypeError::new(format!(
                    "Failed to convert Ruby 'version' return value: {}",
                    e
                ))
            })
        };
        match magnus::Ruby::get() {
            Ok(ruby) => callback(&ruby, self.inner.get_inner_with(&ruby)),
            Err(_) => match self.runtime_dispatcher.dispatch(callback) {
                Ok(result) => result,
                Err(error) => Err(structuredmerge_host_prototype_core::HostPrototypeError::new(
                    format!("Ruby runtime dispatcher failed for method 'version': {}", error),
                )),
            },
        }
    }

    fn initialize(
        &self,
    ) -> std::result::Result<(), structuredmerge_host_prototype_core::HostPrototypeError> {
        if !(self.has_initialize) {
            return Ok(());
        }
        let callback = move |ruby: &magnus::Ruby,
                             value: magnus::Value|
              -> std::result::Result<
            (),
            structuredmerge_host_prototype_core::HostPrototypeError,
        > {
            let val: magnus::Value = match value.funcall::<_, _, magnus::Value>("initialize", ()) {
                Ok(v) => v,
                Err(e) => {
                    return Err(structuredmerge_host_prototype_core::HostPrototypeError::new(
                        format!("Ruby method 'initialize' failed: {}", e),
                    ));
                }
            };
            let _ = val;
            Ok(())
        };
        match magnus::Ruby::get() {
            Ok(ruby) => callback(&ruby, self.inner.get_inner_with(&ruby)),
            Err(_) => match self.runtime_dispatcher.dispatch(callback) {
                Ok(result) => result,
                Err(error) => Err(structuredmerge_host_prototype_core::HostPrototypeError::new(
                    format!("Ruby runtime dispatcher failed for method 'initialize': {}", error),
                )),
            },
        }
    }

    fn shutdown(
        &self,
    ) -> std::result::Result<(), structuredmerge_host_prototype_core::HostPrototypeError> {
        if !(self.has_shutdown) {
            return Ok(());
        }
        let callback = move |ruby: &magnus::Ruby,
                             value: magnus::Value|
              -> std::result::Result<
            (),
            structuredmerge_host_prototype_core::HostPrototypeError,
        > {
            let val: magnus::Value = match value.funcall::<_, _, magnus::Value>("shutdown", ()) {
                Ok(v) => v,
                Err(e) => {
                    return Err(structuredmerge_host_prototype_core::HostPrototypeError::new(
                        format!("Ruby method 'shutdown' failed: {}", e),
                    ));
                }
            };
            let _ = val;
            Ok(())
        };
        match magnus::Ruby::get() {
            Ok(ruby) => callback(&ruby, self.inner.get_inner_with(&ruby)),
            Err(_) => match self.runtime_dispatcher.dispatch(callback) {
                Ok(result) => result,
                Err(error) => Err(structuredmerge_host_prototype_core::HostPrototypeError::new(
                    format!("Ruby runtime dispatcher failed for method 'shutdown': {}", error),
                )),
            },
        }
    }
}

impl structuredmerge_host_prototype_core::ParserHost for RbParserHostBridge {
    fn descriptor(
        &self,
    ) -> std::result::Result<String, structuredmerge_host_prototype_core::HostPrototypeError> {
        let callback = move |ruby: &magnus::Ruby,
                             value: magnus::Value|
              -> std::result::Result<
            String,
            structuredmerge_host_prototype_core::HostPrototypeError,
        > {
            let val: magnus::Value = match value.funcall::<_, _, magnus::Value>("descriptor", ()) {
                Ok(v) => v,
                Err(e) => {
                    return Err(structuredmerge_host_prototype_core::HostPrototypeError::new(
                        format!("Ruby method 'descriptor' failed: {}", e),
                    ));
                }
            };
            <String as magnus::TryConvert>::try_convert(val).map_err(|e| {
                structuredmerge_host_prototype_core::HostPrototypeError::new(format!(
                    "Failed to convert Ruby 'descriptor' return value: {}",
                    e
                ))
            })
        };
        match magnus::Ruby::get() {
            Ok(ruby) => callback(&ruby, self.inner.get_inner_with(&ruby)),
            Err(_) => match self.runtime_dispatcher.dispatch(callback) {
                Ok(result) => result,
                Err(error) => Err(structuredmerge_host_prototype_core::HostPrototypeError::new(
                    format!("Ruby runtime dispatcher failed for method 'descriptor': {}", error),
                )),
            },
        }
    }

    fn probe_batch(
        &self,
        request: Vec<u8>,
    ) -> std::result::Result<Vec<u8>, structuredmerge_host_prototype_core::HostPrototypeError> {
        let request_owned = request;
        let callback = move |ruby: &magnus::Ruby,
                             value: magnus::Value|
              -> std::result::Result<
            Vec<u8>,
            structuredmerge_host_prototype_core::HostPrototypeError,
        > {
            let val: magnus::Value = match value.funcall::<_, _, magnus::Value>(
                "probe_batch",
                (ruby.str_from_slice(AsRef::<[u8]>::as_ref(&request_owned)).as_value(),),
            ) {
                Ok(v) => v,
                Err(e) => {
                    return Err(structuredmerge_host_prototype_core::HostPrototypeError::new(
                        format!("Ruby method 'probe_batch' failed: {}", e),
                    ));
                }
            };
            <magnus::RString as magnus::TryConvert>::try_convert(val)
                .map(|bytes| unsafe { bytes.as_slice() }.to_vec())
                .map_err(|e| {
                    structuredmerge_host_prototype_core::HostPrototypeError::new(format!(
                        "Failed to convert Ruby 'probe_batch' return value: {}",
                        e
                    ))
                })
        };
        match magnus::Ruby::get() {
            Ok(ruby) => callback(&ruby, self.inner.get_inner_with(&ruby)),
            Err(_) => match self.runtime_dispatcher.dispatch(callback) {
                Ok(result) => result,
                Err(error) => Err(structuredmerge_host_prototype_core::HostPrototypeError::new(
                    format!("Ruby runtime dispatcher failed for method 'probe_batch': {}", error),
                )),
            },
        }
    }

    fn parse_batch(
        &self,
        request: Vec<u8>,
    ) -> std::result::Result<Vec<u8>, structuredmerge_host_prototype_core::HostPrototypeError> {
        let request_owned = request;
        let callback = move |ruby: &magnus::Ruby,
                             value: magnus::Value|
              -> std::result::Result<
            Vec<u8>,
            structuredmerge_host_prototype_core::HostPrototypeError,
        > {
            let val: magnus::Value = match value.funcall::<_, _, magnus::Value>(
                "parse_batch",
                (ruby.str_from_slice(AsRef::<[u8]>::as_ref(&request_owned)).as_value(),),
            ) {
                Ok(v) => v,
                Err(e) => {
                    return Err(structuredmerge_host_prototype_core::HostPrototypeError::new(
                        format!("Ruby method 'parse_batch' failed: {}", e),
                    ));
                }
            };
            <magnus::RString as magnus::TryConvert>::try_convert(val)
                .map(|bytes| unsafe { bytes.as_slice() }.to_vec())
                .map_err(|e| {
                    structuredmerge_host_prototype_core::HostPrototypeError::new(format!(
                        "Failed to convert Ruby 'parse_batch' return value: {}",
                        e
                    ))
                })
        };
        match magnus::Ruby::get() {
            Ok(ruby) => callback(&ruby, self.inner.get_inner_with(&ruby)),
            Err(_) => match self.runtime_dispatcher.dispatch(callback) {
                Ok(result) => result,
                Err(error) => Err(structuredmerge_host_prototype_core::HostPrototypeError::new(
                    format!("Ruby runtime dispatcher failed for method 'parse_batch': {}", error),
                )),
            },
        }
    }
}

pub fn register_parser_host(rb_obj: magnus::Value, name: String) -> Result<(), magnus::Error> {
    let required_methods = ["descriptor", "probe_batch", "parse_batch"];
    for method in &required_methods {
        if !rb_obj.respond_to(*method, false).unwrap_or(false) {
            let ruby = unsafe { magnus::Ruby::get_unchecked() };
            return Err(magnus::Error::new(
                ruby.exception_runtime_error(),
                format!("Backend missing required method: {}", method),
            ));
        }
    }
    let wrapper = RbParserHostBridge::new(rb_obj, name)?;
    let arc: Arc<dyn structuredmerge_host_prototype_core::ParserHost> = Arc::new(wrapper);

    structuredmerge_host_prototype_core::plugins::register_parser_host(arc).map_err(|e| {
        let ruby = unsafe { magnus::Ruby::get_unchecked() };
        magnus::Error::new(ruby.exception_runtime_error(), format!("register failed: {}", e))
    })?;
    Ok(())
}

pub fn unregister_parser_host(name: String) -> Result<(), magnus::Error> {
    structuredmerge_host_prototype_core::plugins::unregister_parser_host(&name).map_err(|e| {
        let ruby = unsafe { magnus::Ruby::get_unchecked() };
        magnus::Error::new(ruby.exception_runtime_error(), format!("{}", e))
    })
}

pub fn clear_parser_hosts() -> Result<(), magnus::Error> {
    structuredmerge_host_prototype_core::plugins::clear_parser_hosts().map_err(|e| {
        let ruby = unsafe { magnus::Ruby::get_unchecked() };
        magnus::Error::new(ruby.exception_runtime_error(), format!("{}", e))
    })
}

#[allow(clippy::useless_conversion)]
impl From<structuredmerge_host_prototype_core::HostBatchRequest> for HostBatchRequest {
    fn from(val: structuredmerge_host_prototype_core::HostBatchRequest) -> Self {
        Self {
            schema: val.schema.to_string(),
            items: val.items.into_iter().map(Into::into).collect(),
        }
    }
}

impl From<structuredmerge_host_prototype_core::HostSourceSegment> for HostSourceSegment {
    fn from(val: structuredmerge_host_prototype_core::HostSourceSegment) -> Self {
        Self {
            source_id: val.source_id.to_string(),
            offset: val.offset,
            byte_length: val.byte_length,
            sha256: val.sha256.to_string(),
        }
    }
}

#[magnus::init]
fn ruby_init(ruby: &Ruby) -> Result<(), Error> {
    let module = ruby.define_module("StructuredmergeHostPrototypeCore")?;

    // Ensure JSON library is loaded for Hash#to_json
    let _ = ruby.eval::<magnus::Value>("require \"json\"");

    let class = module.define_class("HostBatchRequest", ruby.class_object())?;

    class.define_singleton_method("new", function!(HostBatchRequest::new, -1))?;

    class.define_method("schema", method!(HostBatchRequest::schema, 0))?;

    class.define_method("items", method!(HostBatchRequest::items, 0))?;

    let class = module.define_class("HostPrototypeError", ruby.class_object())?;

    class.define_method("message", method!(HostPrototypeError::message, 0))?;

    let class = module.define_class("HostSourceSegment", ruby.class_object())?;

    class.define_singleton_method("new", function!(HostSourceSegment::new, -1))?;

    class.define_method("source_id", method!(HostSourceSegment::source_id, 0))?;

    class.define_method("offset", method!(HostSourceSegment::offset, 0))?;

    class.define_method("byte_length", method!(HostSourceSegment::byte_length, 0))?;

    class.define_method("sha256", method!(HostSourceSegment::sha256, 0))?;

    module
        .define_module_function("cancel_identity_worker", function!(cancel_identity_worker, 1))?;

    module.define_module_function(
        "dispatch_identity_worker",
        function!(dispatch_identity_worker, 1),
    )?;

    module.define_module_function(
        "execute_async_identity",
        function!(execute_async_identity_async, 2),
    )?;

    module.define_module_function(
        "execute_detached_identity",
        function!(execute_detached_identity, 5),
    )?;

    module.define_module_function("execute_identity", function!(execute_identity, 2))?;

    module.define_module_function(
        "execute_in_process_identity",
        function!(execute_in_process_identity, 4),
    )?;

    module
        .define_module_function("execute_typed_identity", function!(execute_typed_identity, 5))?;

    module
        .define_module_function("execute_typed_workflow", function!(execute_typed_workflow, 5))?;

    module.define_module_function(
        "identity_worker_cancelled",
        function!(identity_worker_cancelled, 1),
    )?;

    module.define_module_function("merge_json_three_way", function!(merge_json_three_way, 4))?;

    module.define_module_function("merge_json_two_way", function!(merge_json_two_way, 3))?;

    module.define_module_function("parse_with_parser", function!(parse_with_parser, 2))?;

    module.define_module_function("poll_identity_worker", function!(poll_identity_worker, 1))?;

    module
        .define_module_function("prepare_identity_worker", function!(prepare_identity_worker, 2))?;

    module.define_module_function("probe_with_parser", function!(probe_with_parser, 2))?;

    module.define_module_function(
        "register_tslp_parser_host",
        function!(register_tslp_parser_host, 2),
    )?;

    module
        .define_module_function("registered_parser_hosts", function!(registered_parser_hosts, 0))?;

    module.define_module_function(
        "registered_workflow_hosts",
        function!(registered_workflow_hosts, 0),
    )?;

    module.define_module_function("replace_parser_host", function!(replace_parser_host, 2))?;

    module.define_module_function("replace_workflow_host", function!(replace_workflow_host, 2))?;

    module.define_module_function(
        "shutdown_host_runtime",
        function!(shutdown_host_runtime_async, 2),
    )?;

    module.define_module_function("start_host_runtime", function!(start_host_runtime, 0))?;

    module.define_module_function("start_identity_worker", function!(start_identity_worker, 2))?;

    module
        .define_module_function("register_workflow_host", function!(register_workflow_host, 2))?;

    module.define_module_function(
        "unregister_workflow_host",
        function!(unregister_workflow_host, 1),
    )?;

    module.define_module_function("clear_workflow_hosts", function!(clear_workflow_hosts, 0))?;

    module.define_module_function("register_parser_host", function!(register_parser_host, 2))?;

    module
        .define_module_function("unregister_parser_host", function!(unregister_parser_host, 1))?;

    module.define_module_function("clear_parser_hosts", function!(clear_parser_hosts, 0))?;

    Ok(())
}
