// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:cb08063f67ba566999a9dd9b996866235905abf7463f20c26a1578b4a63138b0
// Re-generate with: alef generate
#![allow(dead_code, unused_imports, unused_variables)]
#![allow(
    clippy::too_many_arguments,
    clippy::let_unit_value,
    clippy::needless_borrow,
    clippy::map_identity,
    clippy::just_underscores_and_digits,
    clippy::unnecessary_cast,
    clippy::unused_unit,
    clippy::unwrap_or_default,
    clippy::derivable_impls,
    clippy::needless_borrows_for_generic_args,
    clippy::unnecessary_fallible_conversions,
    clippy::type_complexity,
    clippy::useless_conversion,
    clippy::clone_on_copy
)]

use magnus::{
    Error, IntoValueFromNative, Ruby, function, method, prelude::*, try_convert::TryConvertOwned,
};
use std::sync::Arc;

#[derive(Clone)]
#[magnus::wrap(class = "StructuredmergeHostPrototypeCore::HostPrototypeError")]
pub struct HostPrototypeError {
    inner: Arc<structuredmerge_host_prototype_core::HostPrototypeError>,
}

unsafe impl IntoValueFromNative for HostPrototypeError {}

impl magnus::TryConvert for HostPrototypeError {
    fn try_convert(val: magnus::Value) -> Result<Self, magnus::Error> {
        let r: &HostPrototypeError = magnus::TryConvert::try_convert(val)?;
        Ok(r.clone())
    }
}

unsafe impl TryConvertOwned for HostPrototypeError {}

impl HostPrototypeError {
    fn message(&self) -> String {
        self.inner.message().into()
    }
}

fn execute_identity(provider_name: String, request: Vec<u8>) -> Result<Vec<u8>, Error> {
    let result = structuredmerge_host_prototype_core::execute_identity(provider_name, request)
        .map_err(|e| {
            magnus::Error::new(
                unsafe { Ruby::get_unchecked() }.exception_runtime_error(),
                e.to_string(),
            )
        })?;
    Ok(result.to_vec())
}

fn parse_with_parser(provider_name: String, request: Vec<u8>) -> Result<Vec<u8>, Error> {
    let result = structuredmerge_host_prototype_core::parse_with_parser(provider_name, request)
        .map_err(|e| {
            magnus::Error::new(
                unsafe { Ruby::get_unchecked() }.exception_runtime_error(),
                e.to_string(),
            )
        })?;
    Ok(result.to_vec())
}

fn probe_with_parser(provider_name: String, request: Vec<u8>) -> Result<Vec<u8>, Error> {
    let result = structuredmerge_host_prototype_core::probe_with_parser(provider_name, request)
        .map_err(|e| {
            magnus::Error::new(
                unsafe { Ruby::get_unchecked() }.exception_runtime_error(),
                e.to_string(),
            )
        })?;
    Ok(result.to_vec())
}

fn registered_parser_hosts() -> Vec<String> {
    structuredmerge_host_prototype_core::registered_parser_hosts()
}

fn registered_workflow_hosts() -> Vec<String> {
    structuredmerge_host_prototype_core::registered_workflow_hosts()
}

#[allow(unused_imports)]
use magnus::TryConvert as _;
#[allow(unused_imports)]
use magnus::value::InnerValue as _;
/// Wrapper that bridges a foreign Rb object to the `WorkflowHost` trait.
pub struct RbWorkflowHostBridge {
    inner: magnus::value::Opaque<magnus::Value>,
    cached_name: String,
    has_initialize: bool,
    has_shutdown: bool,
}

impl std::fmt::Debug for RbWorkflowHostBridge {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "RbWorkflowHostBridge")
    }
}

impl RbWorkflowHostBridge {
    /// Create a new bridge wrapping a Ruby object.
    /// Validates that the Ruby object responds to all required methods.
    pub fn new(rb_obj: magnus::Value, name: String) -> Result<Self, magnus::Error> {
        if !rb_obj.respond_to("descriptor", false).unwrap_or(false) {
            let ruby = unsafe { magnus::Ruby::get_unchecked() };
            return Err(magnus::Error::new(
                ruby.exception_runtime_error(),
                format!("Ruby object missing required method: {}", "descriptor"),
            ));
        }
        if !rb_obj.respond_to("execute_batch", false).unwrap_or(false) {
            let ruby = unsafe { magnus::Ruby::get_unchecked() };
            return Err(magnus::Error::new(
                ruby.exception_runtime_error(),
                format!("Ruby object missing required method: {}", "execute_batch"),
            ));
        }
        Ok(Self {
            inner: magnus::value::Opaque::from(rb_obj),
            cached_name: name,
            has_initialize: rb_obj.respond_to("initialize", false).unwrap_or(false),
            has_shutdown: rb_obj.respond_to("shutdown", false).unwrap_or(false),
        })
    }
}

impl structuredmerge_host_prototype_core::Plugin for RbWorkflowHostBridge {
    fn name(&self) -> &str {
        &self.cached_name
    }

    fn version(
        &self,
    ) -> std::result::Result<String, structuredmerge_host_prototype_core::HostPrototypeError> {
        // SAFETY: bridge methods are only invoked from threads holding the GVL
        let ruby = unsafe { magnus::Ruby::get_unchecked() };
        let value = self.inner.get_inner_with(&ruby);
        let val: magnus::Value = match value.funcall::<_, _, magnus::Value>("version", ()) {
            Ok(v) => v,
            Err(e) => {
                return Err(structuredmerge_host_prototype_core::HostPrototypeError::new(format!(
                    "Ruby method 'version' failed: {}",
                    e
                )));
            }
        };
        <String as magnus::TryConvert>::try_convert(val).map_err(|e| {
            structuredmerge_host_prototype_core::HostPrototypeError::new(format!(
                "Failed to convert Ruby 'version' return value: {}",
                e
            ))
        })
    }

    fn initialize(
        &self,
    ) -> std::result::Result<(), structuredmerge_host_prototype_core::HostPrototypeError> {
        if !(self.has_initialize) {
            return Ok(());
        }
        // SAFETY: bridge methods are only invoked from threads holding the GVL
        let ruby = unsafe { magnus::Ruby::get_unchecked() };
        let value = self.inner.get_inner_with(&ruby);
        let val: magnus::Value = match value.funcall::<_, _, magnus::Value>("initialize", ()) {
            Ok(v) => v,
            Err(e) => {
                return Err(structuredmerge_host_prototype_core::HostPrototypeError::new(format!(
                    "Ruby method 'initialize' failed: {}",
                    e
                )));
            }
        };
        let _ = val;
        Ok(())
    }

    fn shutdown(
        &self,
    ) -> std::result::Result<(), structuredmerge_host_prototype_core::HostPrototypeError> {
        if !(self.has_shutdown) {
            return Ok(());
        }
        // SAFETY: bridge methods are only invoked from threads holding the GVL
        let ruby = unsafe { magnus::Ruby::get_unchecked() };
        let value = self.inner.get_inner_with(&ruby);
        let val: magnus::Value = match value.funcall::<_, _, magnus::Value>("shutdown", ()) {
            Ok(v) => v,
            Err(e) => {
                return Err(structuredmerge_host_prototype_core::HostPrototypeError::new(format!(
                    "Ruby method 'shutdown' failed: {}",
                    e
                )));
            }
        };
        let _ = val;
        Ok(())
    }
}

impl structuredmerge_host_prototype_core::WorkflowHost for RbWorkflowHostBridge {
    fn descriptor(
        &self,
    ) -> std::result::Result<String, structuredmerge_host_prototype_core::HostPrototypeError> {
        // SAFETY: bridge methods are only invoked from threads holding the GVL
        let ruby = unsafe { magnus::Ruby::get_unchecked() };
        let value = self.inner.get_inner_with(&ruby);
        let val: magnus::Value = match value.funcall::<_, _, magnus::Value>("descriptor", ()) {
            Ok(v) => v,
            Err(e) => {
                return Err(structuredmerge_host_prototype_core::HostPrototypeError::new(format!(
                    "Ruby method 'descriptor' failed: {}",
                    e
                )));
            }
        };
        <String as magnus::TryConvert>::try_convert(val).map_err(|e| {
            structuredmerge_host_prototype_core::HostPrototypeError::new(format!(
                "Failed to convert Ruby 'descriptor' return value: {}",
                e
            ))
        })
    }

    fn execute_batch(
        &self,
        request: Vec<u8>,
    ) -> std::result::Result<Vec<u8>, structuredmerge_host_prototype_core::HostPrototypeError> {
        // SAFETY: bridge methods are only invoked from threads holding the GVL
        let ruby = unsafe { magnus::Ruby::get_unchecked() };
        let value = self.inner.get_inner_with(&ruby);
        let val: magnus::Value = match value.funcall::<_, _, magnus::Value>(
            "execute_batch",
            ({
                let ruby = unsafe { magnus::Ruby::get_unchecked() };
                ruby.str_from_slice(AsRef::<[u8]>::as_ref(&request)).as_value()
            },),
        ) {
            Ok(v) => v,
            Err(e) => {
                return Err(structuredmerge_host_prototype_core::HostPrototypeError::new(format!(
                    "Ruby method 'execute_batch' failed: {}",
                    e
                )));
            }
        };
        <magnus::RString as magnus::TryConvert>::try_convert(val)
            .map(|bytes| unsafe { bytes.as_slice() }.to_vec())
            .map_err(|e| {
                structuredmerge_host_prototype_core::HostPrototypeError::new(format!(
                    "Failed to convert Ruby 'execute_batch' return value: {}",
                    e
                ))
            })
    }
}

pub fn register_workflow_host(rb_obj: magnus::Value, name: String) -> Result<(), magnus::Error> {
    let required_methods = ["descriptor", "execute_batch"];
    for method in &required_methods {
        if !rb_obj.respond_to(*method, false).unwrap_or(false) {
            let ruby = unsafe { magnus::Ruby::get_unchecked() };
            return Err(magnus::Error::new(
                ruby.exception_runtime_error(),
                format!("Backend missing required method: {}", method),
            ));
        }
    }
    let wrapper = RbWorkflowHostBridge::new(rb_obj, name)?;
    let arc: Arc<dyn structuredmerge_host_prototype_core::WorkflowHost> = Arc::new(wrapper);

    structuredmerge_host_prototype_core::plugins::register_workflow_host(arc).map_err(|e| {
        let ruby = unsafe { magnus::Ruby::get_unchecked() };
        magnus::Error::new(ruby.exception_runtime_error(), format!("register failed: {}", e))
    })?;
    Ok(())
}

pub fn unregister_workflow_host(name: String) -> Result<(), magnus::Error> {
    structuredmerge_host_prototype_core::plugins::unregister_workflow_host(&name).map_err(|e| {
        let ruby = unsafe { magnus::Ruby::get_unchecked() };
        magnus::Error::new(ruby.exception_runtime_error(), format!("{}", e))
    })
}

pub fn clear_workflow_hosts() -> Result<(), magnus::Error> {
    structuredmerge_host_prototype_core::plugins::clear_workflow_hosts().map_err(|e| {
        let ruby = unsafe { magnus::Ruby::get_unchecked() };
        magnus::Error::new(ruby.exception_runtime_error(), format!("{}", e))
    })
}

#[allow(unused_imports)]
use magnus::TryConvert as _;
#[allow(unused_imports)]
use magnus::value::InnerValue as _;
/// Wrapper that bridges a foreign Rb object to the `ParserHost` trait.
pub struct RbParserHostBridge {
    inner: magnus::value::Opaque<magnus::Value>,
    cached_name: String,
    has_initialize: bool,
    has_shutdown: bool,
}

impl std::fmt::Debug for RbParserHostBridge {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "RbParserHostBridge")
    }
}

impl RbParserHostBridge {
    /// Create a new bridge wrapping a Ruby object.
    /// Validates that the Ruby object responds to all required methods.
    pub fn new(rb_obj: magnus::Value, name: String) -> Result<Self, magnus::Error> {
        if !rb_obj.respond_to("descriptor", false).unwrap_or(false) {
            let ruby = unsafe { magnus::Ruby::get_unchecked() };
            return Err(magnus::Error::new(
                ruby.exception_runtime_error(),
                format!("Ruby object missing required method: {}", "descriptor"),
            ));
        }
        if !rb_obj.respond_to("probe_batch", false).unwrap_or(false) {
            let ruby = unsafe { magnus::Ruby::get_unchecked() };
            return Err(magnus::Error::new(
                ruby.exception_runtime_error(),
                format!("Ruby object missing required method: {}", "probe_batch"),
            ));
        }
        if !rb_obj.respond_to("parse_batch", false).unwrap_or(false) {
            let ruby = unsafe { magnus::Ruby::get_unchecked() };
            return Err(magnus::Error::new(
                ruby.exception_runtime_error(),
                format!("Ruby object missing required method: {}", "parse_batch"),
            ));
        }
        Ok(Self {
            inner: magnus::value::Opaque::from(rb_obj),
            cached_name: name,
            has_initialize: rb_obj.respond_to("initialize", false).unwrap_or(false),
            has_shutdown: rb_obj.respond_to("shutdown", false).unwrap_or(false),
        })
    }
}

impl structuredmerge_host_prototype_core::Plugin for RbParserHostBridge {
    fn name(&self) -> &str {
        &self.cached_name
    }

    fn version(
        &self,
    ) -> std::result::Result<String, structuredmerge_host_prototype_core::HostPrototypeError> {
        // SAFETY: bridge methods are only invoked from threads holding the GVL
        let ruby = unsafe { magnus::Ruby::get_unchecked() };
        let value = self.inner.get_inner_with(&ruby);
        let val: magnus::Value = match value.funcall::<_, _, magnus::Value>("version", ()) {
            Ok(v) => v,
            Err(e) => {
                return Err(structuredmerge_host_prototype_core::HostPrototypeError::new(format!(
                    "Ruby method 'version' failed: {}",
                    e
                )));
            }
        };
        <String as magnus::TryConvert>::try_convert(val).map_err(|e| {
            structuredmerge_host_prototype_core::HostPrototypeError::new(format!(
                "Failed to convert Ruby 'version' return value: {}",
                e
            ))
        })
    }

    fn initialize(
        &self,
    ) -> std::result::Result<(), structuredmerge_host_prototype_core::HostPrototypeError> {
        if !(self.has_initialize) {
            return Ok(());
        }
        // SAFETY: bridge methods are only invoked from threads holding the GVL
        let ruby = unsafe { magnus::Ruby::get_unchecked() };
        let value = self.inner.get_inner_with(&ruby);
        let val: magnus::Value = match value.funcall::<_, _, magnus::Value>("initialize", ()) {
            Ok(v) => v,
            Err(e) => {
                return Err(structuredmerge_host_prototype_core::HostPrototypeError::new(format!(
                    "Ruby method 'initialize' failed: {}",
                    e
                )));
            }
        };
        let _ = val;
        Ok(())
    }

    fn shutdown(
        &self,
    ) -> std::result::Result<(), structuredmerge_host_prototype_core::HostPrototypeError> {
        if !(self.has_shutdown) {
            return Ok(());
        }
        // SAFETY: bridge methods are only invoked from threads holding the GVL
        let ruby = unsafe { magnus::Ruby::get_unchecked() };
        let value = self.inner.get_inner_with(&ruby);
        let val: magnus::Value = match value.funcall::<_, _, magnus::Value>("shutdown", ()) {
            Ok(v) => v,
            Err(e) => {
                return Err(structuredmerge_host_prototype_core::HostPrototypeError::new(format!(
                    "Ruby method 'shutdown' failed: {}",
                    e
                )));
            }
        };
        let _ = val;
        Ok(())
    }
}

impl structuredmerge_host_prototype_core::ParserHost for RbParserHostBridge {
    fn descriptor(
        &self,
    ) -> std::result::Result<String, structuredmerge_host_prototype_core::HostPrototypeError> {
        // SAFETY: bridge methods are only invoked from threads holding the GVL
        let ruby = unsafe { magnus::Ruby::get_unchecked() };
        let value = self.inner.get_inner_with(&ruby);
        let val: magnus::Value = match value.funcall::<_, _, magnus::Value>("descriptor", ()) {
            Ok(v) => v,
            Err(e) => {
                return Err(structuredmerge_host_prototype_core::HostPrototypeError::new(format!(
                    "Ruby method 'descriptor' failed: {}",
                    e
                )));
            }
        };
        <String as magnus::TryConvert>::try_convert(val).map_err(|e| {
            structuredmerge_host_prototype_core::HostPrototypeError::new(format!(
                "Failed to convert Ruby 'descriptor' return value: {}",
                e
            ))
        })
    }

    fn probe_batch(
        &self,
        request: Vec<u8>,
    ) -> std::result::Result<Vec<u8>, structuredmerge_host_prototype_core::HostPrototypeError> {
        // SAFETY: bridge methods are only invoked from threads holding the GVL
        let ruby = unsafe { magnus::Ruby::get_unchecked() };
        let value = self.inner.get_inner_with(&ruby);
        let val: magnus::Value = match value.funcall::<_, _, magnus::Value>(
            "probe_batch",
            ({
                let ruby = unsafe { magnus::Ruby::get_unchecked() };
                ruby.str_from_slice(AsRef::<[u8]>::as_ref(&request)).as_value()
            },),
        ) {
            Ok(v) => v,
            Err(e) => {
                return Err(structuredmerge_host_prototype_core::HostPrototypeError::new(format!(
                    "Ruby method 'probe_batch' failed: {}",
                    e
                )));
            }
        };
        <magnus::RString as magnus::TryConvert>::try_convert(val)
            .map(|bytes| unsafe { bytes.as_slice() }.to_vec())
            .map_err(|e| {
                structuredmerge_host_prototype_core::HostPrototypeError::new(format!(
                    "Failed to convert Ruby 'probe_batch' return value: {}",
                    e
                ))
            })
    }

    fn parse_batch(
        &self,
        request: Vec<u8>,
    ) -> std::result::Result<Vec<u8>, structuredmerge_host_prototype_core::HostPrototypeError> {
        // SAFETY: bridge methods are only invoked from threads holding the GVL
        let ruby = unsafe { magnus::Ruby::get_unchecked() };
        let value = self.inner.get_inner_with(&ruby);
        let val: magnus::Value = match value.funcall::<_, _, magnus::Value>(
            "parse_batch",
            ({
                let ruby = unsafe { magnus::Ruby::get_unchecked() };
                ruby.str_from_slice(AsRef::<[u8]>::as_ref(&request)).as_value()
            },),
        ) {
            Ok(v) => v,
            Err(e) => {
                return Err(structuredmerge_host_prototype_core::HostPrototypeError::new(format!(
                    "Ruby method 'parse_batch' failed: {}",
                    e
                )));
            }
        };
        <magnus::RString as magnus::TryConvert>::try_convert(val)
            .map(|bytes| unsafe { bytes.as_slice() }.to_vec())
            .map_err(|e| {
                structuredmerge_host_prototype_core::HostPrototypeError::new(format!(
                    "Failed to convert Ruby 'parse_batch' return value: {}",
                    e
                ))
            })
    }
}

pub fn register_parser_host(rb_obj: magnus::Value, name: String) -> Result<(), magnus::Error> {
    let required_methods = ["descriptor", "probe_batch", "parse_batch"];
    for method in &required_methods {
        if !rb_obj.respond_to(*method, false).unwrap_or(false) {
            let ruby = unsafe { magnus::Ruby::get_unchecked() };
            return Err(magnus::Error::new(
                ruby.exception_runtime_error(),
                format!("Backend missing required method: {}", method),
            ));
        }
    }
    let wrapper = RbParserHostBridge::new(rb_obj, name)?;
    let arc: Arc<dyn structuredmerge_host_prototype_core::ParserHost> = Arc::new(wrapper);

    structuredmerge_host_prototype_core::plugins::register_parser_host(arc).map_err(|e| {
        let ruby = unsafe { magnus::Ruby::get_unchecked() };
        magnus::Error::new(ruby.exception_runtime_error(), format!("register failed: {}", e))
    })?;
    Ok(())
}

pub fn unregister_parser_host(name: String) -> Result<(), magnus::Error> {
    structuredmerge_host_prototype_core::plugins::unregister_parser_host(&name).map_err(|e| {
        let ruby = unsafe { magnus::Ruby::get_unchecked() };
        magnus::Error::new(ruby.exception_runtime_error(), format!("{}", e))
    })
}

pub fn clear_parser_hosts() -> Result<(), magnus::Error> {
    structuredmerge_host_prototype_core::plugins::clear_parser_hosts().map_err(|e| {
        let ruby = unsafe { magnus::Ruby::get_unchecked() };
        magnus::Error::new(ruby.exception_runtime_error(), format!("{}", e))
    })
}

#[magnus::init]
fn ruby_init(ruby: &Ruby) -> Result<(), Error> {
    let module = ruby.define_module("StructuredmergeHostPrototypeCore")?;

    // Ensure JSON library is loaded for Hash#to_json
    let _ = ruby.eval::<magnus::Value>("require \"json\"");

    let class = module.define_class("HostPrototypeError", ruby.class_object())?;

    class.define_method("message", method!(HostPrototypeError::message, 0))?;

    module.define_module_function("execute_identity", function!(execute_identity, 2))?;

    module.define_module_function("parse_with_parser", function!(parse_with_parser, 2))?;

    module.define_module_function("probe_with_parser", function!(probe_with_parser, 2))?;

    module
        .define_module_function("registered_parser_hosts", function!(registered_parser_hosts, 0))?;

    module.define_module_function(
        "registered_workflow_hosts",
        function!(registered_workflow_hosts, 0),
    )?;

    module
        .define_module_function("register_workflow_host", function!(register_workflow_host, 2))?;

    module.define_module_function(
        "unregister_workflow_host",
        function!(unregister_workflow_host, 1),
    )?;

    module.define_module_function("clear_workflow_hosts", function!(clear_workflow_hosts, 0))?;

    module.define_module_function("register_parser_host", function!(register_parser_host, 2))?;

    module
        .define_module_function("unregister_parser_host", function!(unregister_parser_host, 1))?;

    module.define_module_function("clear_parser_hosts", function!(clear_parser_hosts, 0))?;

    Ok(())
}
