# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d3c98771d296f361ab06fc631a1a4d967ccc73db52615d82a8124c14bf809aba
# To regenerate: alef generate
# To verify freshness: alef verify
# frozen_string_literal: true

require "json"
require "sorbet-runtime"
require "rbconfig"

extension_name = "structuredmerge_host_prototype_core_rb"
# Ruby may expose more than one shared-library extension via DLEXT/DLEXT2.
dlexts = [RbConfig::CONFIG["DLEXT"], RbConfig::CONFIG["DLEXT2"]].compact.uniq
ruby_abi = RbConfig::CONFIG.fetch("ruby_version")

library_candidates = dlexts.flat_map do |dlext|
  [
    File.join(__dir__, "..", extension_name, ruby_abi, "#{extension_name}.#{dlext}"),
    File.join(__dir__, "..", extension_name, ruby_abi, "lib#{extension_name}.#{dlext}"),
    File.join(__dir__, "..", "#{extension_name}.#{dlext}"),
    File.join(__dir__, "..", "lib#{extension_name}.#{dlext}"),
  ]
end

expanded_candidates = library_candidates.map { |path| File.expand_path(path) }
native_extension = expanded_candidates.find { |path| File.file?(path) }

unless native_extension
  raise(
    LoadError,
    "cannot find #{extension_name} native extension for Ruby ABI #{ruby_abi}; " \
      "searched: #{expanded_candidates.join(", ")}"
  )
end

require native_extension
module StructuredmergeHostPrototype
  # Re-export public types from the native extension (curated list, excludes Update/Builder types)
  HostBatchRequest = StructuredmergeHostPrototypeCore.const_get(:HostBatchRequest)
  HostSourceSegment = StructuredmergeHostPrototypeCore.const_get(:HostSourceSegment)
  # Re-export public module functions from the native extension (curated list)
  define_singleton_method(:cancel_identity_worker) { |*args, **kwargs, &blk| StructuredmergeHostPrototypeCore.public_send(:cancel_identity_worker, *args, **kwargs, &blk) }
  define_singleton_method(:capability_manifest) { |*args, **kwargs, &blk| StructuredmergeHostPrototypeCore.public_send(:capability_manifest, *args, **kwargs, &blk) }
  define_singleton_method(:clear_parser_hosts) { |*args, **kwargs, &blk| StructuredmergeHostPrototypeCore.public_send(:clear_parser_hosts, *args, **kwargs, &blk) }
  define_singleton_method(:clear_workflow_hosts) { |*args, **kwargs, &blk| StructuredmergeHostPrototypeCore.public_send(:clear_workflow_hosts, *args, **kwargs, &blk) }
  define_singleton_method(:dispatch_identity_worker) { |*args, **kwargs, &blk| StructuredmergeHostPrototypeCore.public_send(:dispatch_identity_worker, *args, **kwargs, &blk) }
  define_singleton_method(:execute_async_identity) { |*args, **kwargs, &blk| StructuredmergeHostPrototypeCore.public_send(:execute_async_identity, *args, **kwargs, &blk) }
  define_singleton_method(:execute_detached_identity) { |*args, **kwargs, &blk| StructuredmergeHostPrototypeCore.public_send(:execute_detached_identity, *args, **kwargs, &blk) }
  define_singleton_method(:execute_identity) { |*args, **kwargs, &blk| StructuredmergeHostPrototypeCore.public_send(:execute_identity, *args, **kwargs, &blk) }
  define_singleton_method(:execute_in_process_identity) { |*args, **kwargs, &blk| StructuredmergeHostPrototypeCore.public_send(:execute_in_process_identity, *args, **kwargs, &blk) }
  define_singleton_method(:execute_typed_identity) { |*args, **kwargs, &blk| StructuredmergeHostPrototypeCore.public_send(:execute_typed_identity, *args, **kwargs, &blk) }
  define_singleton_method(:execute_typed_workflow) { |*args, **kwargs, &blk| StructuredmergeHostPrototypeCore.public_send(:execute_typed_workflow, *args, **kwargs, &blk) }
  define_singleton_method(:identity_worker_cancelled) { |*args, **kwargs, &blk| StructuredmergeHostPrototypeCore.public_send(:identity_worker_cancelled, *args, **kwargs, &blk) }
  define_singleton_method(:merge_go_three_way) { |*args, **kwargs, &blk| StructuredmergeHostPrototypeCore.public_send(:merge_go_three_way, *args, **kwargs, &blk) }
  define_singleton_method(:merge_go_two_way) { |*args, **kwargs, &blk| StructuredmergeHostPrototypeCore.public_send(:merge_go_two_way, *args, **kwargs, &blk) }
  define_singleton_method(:merge_json_three_way) { |*args, **kwargs, &blk| StructuredmergeHostPrototypeCore.public_send(:merge_json_three_way, *args, **kwargs, &blk) }
  define_singleton_method(:merge_json_two_way) { |*args, **kwargs, &blk| StructuredmergeHostPrototypeCore.public_send(:merge_json_two_way, *args, **kwargs, &blk) }
  define_singleton_method(:merge_rust_three_way) { |*args, **kwargs, &blk| StructuredmergeHostPrototypeCore.public_send(:merge_rust_three_way, *args, **kwargs, &blk) }
  define_singleton_method(:merge_rust_two_way) { |*args, **kwargs, &blk| StructuredmergeHostPrototypeCore.public_send(:merge_rust_two_way, *args, **kwargs, &blk) }
  define_singleton_method(:merge_typescript_three_way) { |*args, **kwargs, &blk| StructuredmergeHostPrototypeCore.public_send(:merge_typescript_three_way, *args, **kwargs, &blk) }
  define_singleton_method(:merge_typescript_two_way) { |*args, **kwargs, &blk| StructuredmergeHostPrototypeCore.public_send(:merge_typescript_two_way, *args, **kwargs, &blk) }
  define_singleton_method(:parse_go_analysis) { |*args, **kwargs, &blk| StructuredmergeHostPrototypeCore.public_send(:parse_go_analysis, *args, **kwargs, &blk) }
  define_singleton_method(:parse_json_analysis) { |*args, **kwargs, &blk| StructuredmergeHostPrototypeCore.public_send(:parse_json_analysis, *args, **kwargs, &blk) }
  define_singleton_method(:parse_normalized_with_tslp) { |*args, **kwargs, &blk| StructuredmergeHostPrototypeCore.public_send(:parse_normalized_with_tslp, *args, **kwargs, &blk) }
  define_singleton_method(:parse_rust_analysis) { |*args, **kwargs, &blk| StructuredmergeHostPrototypeCore.public_send(:parse_rust_analysis, *args, **kwargs, &blk) }
  define_singleton_method(:parse_typescript_analysis) { |*args, **kwargs, &blk| StructuredmergeHostPrototypeCore.public_send(:parse_typescript_analysis, *args, **kwargs, &blk) }
  define_singleton_method(:parse_with_parser) { |*args, **kwargs, &blk| StructuredmergeHostPrototypeCore.public_send(:parse_with_parser, *args, **kwargs, &blk) }
  define_singleton_method(:poll_identity_worker) { |*args, **kwargs, &blk| StructuredmergeHostPrototypeCore.public_send(:poll_identity_worker, *args, **kwargs, &blk) }
  define_singleton_method(:prepare_identity_worker) { |*args, **kwargs, &blk| StructuredmergeHostPrototypeCore.public_send(:prepare_identity_worker, *args, **kwargs, &blk) }
  define_singleton_method(:probe_with_parser) { |*args, **kwargs, &blk| StructuredmergeHostPrototypeCore.public_send(:probe_with_parser, *args, **kwargs, &blk) }
  define_singleton_method(:register_tslp_parser_host) { |*args, **kwargs, &blk| StructuredmergeHostPrototypeCore.public_send(:register_tslp_parser_host, *args, **kwargs, &blk) }
  define_singleton_method(:registered_parser_hosts) { |*args, **kwargs, &blk| StructuredmergeHostPrototypeCore.public_send(:registered_parser_hosts, *args, **kwargs, &blk) }
  define_singleton_method(:registered_workflow_hosts) { |*args, **kwargs, &blk| StructuredmergeHostPrototypeCore.public_send(:registered_workflow_hosts, *args, **kwargs, &blk) }
  define_singleton_method(:replace_parser_host) { |*args, **kwargs, &blk| StructuredmergeHostPrototypeCore.public_send(:replace_parser_host, *args, **kwargs, &blk) }
  define_singleton_method(:replace_workflow_host) { |*args, **kwargs, &blk| StructuredmergeHostPrototypeCore.public_send(:replace_workflow_host, *args, **kwargs, &blk) }
  define_singleton_method(:shutdown_host_runtime) { |*args, **kwargs, &blk| StructuredmergeHostPrototypeCore.public_send(:shutdown_host_runtime, *args, **kwargs, &blk) }
  define_singleton_method(:start_host_runtime) { |*args, **kwargs, &blk| StructuredmergeHostPrototypeCore.public_send(:start_host_runtime, *args, **kwargs, &blk) }
  define_singleton_method(:start_identity_worker) { |*args, **kwargs, &blk| StructuredmergeHostPrototypeCore.public_send(:start_identity_worker, *args, **kwargs, &blk) }
  define_singleton_method(:unregister_parser_host) { |*args, **kwargs, &blk| StructuredmergeHostPrototypeCore.public_send(:unregister_parser_host, *args, **kwargs, &blk) }
  define_singleton_method(:unregister_workflow_host) { |*args, **kwargs, &blk| StructuredmergeHostPrototypeCore.public_send(:unregister_workflow_host, *args, **kwargs, &blk) }
end
