# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e3498ba6a9dc750306c78c8d9655b5990453fcf5c42e434605269924b60f055c
# To regenerate: alef generate
# To verify freshness: alef verify
# frozen_string_literal: true

require "json"
require "sorbet-runtime"
require "rbconfig"

extension_name = "structuredmerge_host_prototype_core_rb"
# Ruby may expose more than one shared-library extension via DLEXT/DLEXT2.
dlexts = [RbConfig::CONFIG["DLEXT"], RbConfig::CONFIG["DLEXT2"]].compact.uniq
ruby_abi = RbConfig::CONFIG.fetch("ruby_version")

library_candidates = dlexts.flat_map do |dlext|
  [
    File.join(__dir__, "..", extension_name, ruby_abi, "#{extension_name}.#{dlext}"),
    File.join(__dir__, "..", extension_name, ruby_abi, "lib#{extension_name}.#{dlext}"),
    File.join(__dir__, "..", "#{extension_name}.#{dlext}"),
    File.join(__dir__, "..", "lib#{extension_name}.#{dlext}"),
  ]
end

expanded_candidates = library_candidates.map { |path| File.expand_path(path) }
native_extension = expanded_candidates.find { |path| File.file?(path) }

unless native_extension
  raise(
    LoadError,
    "cannot find #{extension_name} native extension for Ruby ABI #{ruby_abi}; " \
      "searched: #{expanded_candidates.join(", ")}"
  )
end

require native_extension
module StructuredmergeHostPrototype
  # Re-export public types from the native extension (curated list, excludes Update/Builder types)
  # Re-export public module functions from the native extension (curated list)
  define_singleton_method(:clear_workflow_hosts) { |*args, **kwargs, &blk| StructuredmergeHostPrototypeCore.public_send(:clear_workflow_hosts, *args, **kwargs, &blk) }
  define_singleton_method(:execute_identity) { |*args, **kwargs, &blk| StructuredmergeHostPrototypeCore.public_send(:execute_identity, *args, **kwargs, &blk) }
  define_singleton_method(:registered_workflow_hosts) { |*args, **kwargs, &blk| StructuredmergeHostPrototypeCore.public_send(:registered_workflow_hosts, *args, **kwargs, &blk) }
  define_singleton_method(:unregister_workflow_host) { |*args, **kwargs, &blk| StructuredmergeHostPrototypeCore.public_send(:unregister_workflow_host, *args, **kwargs, &blk) }
end
