# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:8bcd29eb49c321bb6d82d838965199d85f1ddf9369026bdd47641f03921b2449
# To regenerate: alef generate
# To verify freshness: alef verify
# frozen_string_literal: true

module StructuredmergeHostPrototype
  ## The version string for this package.
  VERSION = "0.2.0"
end
